version: '3.9'

services:
  app:
    image: app:latest
    container_name: app
    ports:
      - "4000:4000"
    env_file:
      - .env.production
  page:
    image: page:latest
    container_name: page
    ports:
      - "4002:4002"
    env_file:
      - .env.production
  server:
    image: server:latest
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - .env.production