version: '3.9'

services:
  varaious-page:
    image: varaious-page:latest
    container_name: varaious-page
    ports:
      - "4002:4002"
    env_file:
      - path: .env.production
        required : true


